#!/usr/bin/env bash

source "$HOME/dotfiles/vendor/fasd/fasd"
eval "$(fasd --init zsh-hook)"

z() {
  local dir
  dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
}

v() {
  local file
  file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m)" && vim "${file}" || return 1
}
