# Relative path to the script directory
scripts: script

# Check for the following dependencies in PATH
dependencies:
  - bash
  - awk
  - sed
  - tr
  - head

# Environment variables
env:
  HELLO: "Hello World!"

# Enable scripts from manage repository
enable:
  - help
  - test

# Default script to execute
default: help

#
# script: test
#
# Relative path to the test directory
test:
  tests: script/test

