---
- hosts: all
  gather_facts: yes
  tasks:
    - name: check for accurate date
      when: "{{ (ansible_date_time['year']|int) < 2016 }}"
      fail:
        msg: >
          Your machines have a misconfigured date. Please run
          `ansible --become all -a 'date --set="yyyymmdd"'` with the current
          date before continuing.
    - name: check for compatible centos version
      when: ansible_distribution_version | version_compare("7.2", "<")
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of Centos.
          Please run the playbook playbooks/upgrade-packages.yml before
          continuing.
    - name: check for compatible kernel version
      when: >
        ansible_kernel | version_compare("3.10.0-327", "<")
        and provider != "digitalocean"
        and provider != "packer"
      fail:
        msg: >
          Your hosts don't appear to be running a compatible version of the
          Linux kernel. Please run the playbook playbooks/upgrade-packages.yml
          before continuing.
